# Generated by Django 6.0.2 on 2026-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('provider_id', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name', 'country_code')},
            },
        ),
    ]
